GET http://localhost:8080/devops_starter_war_exploded/api/person/all

###

POST https://vincehub.dk/devops-starter/api/person/
Content-Type: application/json

{
  "fName": "Vincent",
  "lName": "Buchholz",
  "phone": "22551133"
}

###
PUT https://vincehub.dk/devops-starter/api/person/edit/2
Content-Type: application/json

{
  "lName": "Nymand",
  "phone": "22252225"
}

###
DELETE http://localhost:8080/devops_starter_war_exploded/api/person/6
